name: Bump version and tag
on:
  push:
    branches:
      - main 
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        DEFAULT_BUMP: "revision"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
  release-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release && strip target/release/goa && mv target/release/goa target/release/goa_amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/goa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/goa.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: cargo build --all --release && strip target/release/goa && mv target/release/goa target/release/goa_darwin

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/goa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
