name: Bump version and tag
permissions: read-all
on:
  push:
    branches:
      - main 
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      with:
        fetch-depth: '0'
        ssh-key: "${{ secrets.COMMIT_KEY }}"

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@3272e7a58f6c71ee9ede35f53b114e1bb9a91347
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: "revision"
