name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  build-ubuntu-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Get tag name
        id: tag_name
        run: echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build
        run: cargo build --all --release && mv target/release/goa target/release/goa_amd64

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          release_name: ${{ steps.tag_name.outputs.SOURCE_TAG }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/goa_amd64
          asset_name: goa_amd64
          tag: ${{ github.ref }}
          overwrite: true
          body: ${{ steps.github_release.outputs.changelog }}

  build-aarch64-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-dev musl-tools
          cargo install cross --git https://github.com/cross-rs/cross
          cross build --target=aarch64-unknown-linux-gnu --release && mv target/aarch64-unknown-linux-gnu/release/goa target/aarch64-unknown-linux-gnu/release/goa_aarch64

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/aarch64-unknown-linux-gnu/release/goa_aarch64
          asset_name: goa_aarch64
          tag: ${{ github.ref }}
          overwrite: true

  build-arm-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: arm-unknown-linux-gnueabihf

      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-dev musl-tools
          cargo install cross --git https://github.com/cross-rs/cross
          cross build --target=arm-unknown-linux-gnueabihf --release && mv target/arm-unknown-linux-gnueabihf/release/goa target/arm-unknown-linux-gnueabihf/release/goa_arm

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/arm-unknown-linux-gnueabihf/release/goa_arm
          asset_name: goa_arm
          tag: ${{ github.ref }}
          overwrite: true

  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --all --release

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/goa.exe
          asset_name: goa.exe
          tag: ${{ github.ref }}
          overwrite: true

  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin

      - name: Build for mac
        run: cargo build --all --release && mv target/release/goa target/release/goa_darwin

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/goa_darwin
          asset_name: goa_darwin
          tag: ${{ github.ref }}
          overwrite: true
