name: Rust
permissions: read-all
on:
  push:
    branches: [ feature* ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_n_lint:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
    - name: Install latest rust toolchain
      uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
      with:
        toolchain: stable
        default: true
        override: true
    - name: cargo build
      run: cargo build --verbose
    - name: cargo clippy
      run: cargo clippy --verbose
    
  functional_test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        rust: [stable]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
    - name: Install latest rust toolchain
      uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
      with:
        toolchain: stable
        default: true
        override: true
    - name: cargo test
      run: export TMPDIR=$HOME; cargo test --verbose
