name: Rust
permissions: read-all
on:
  push:
    branches: [ feature* ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_n_lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - name: Install latest rust toolchain
      uses: dtolnay/rust-toolchain@631a55b12751854ce901bb631d5902ceb48146f7 # stable
    - name: cargo build
      run: cargo build --verbose
    - name: cargo clippy
      run: cargo clippy --verbose

  functional_test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        rust: [stable]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - name: Install latest rust toolchain
      uses: dtolnay/rust-toolchain@631a55b12751854ce901bb631d5902ceb48146f7 # stable
    - name: cargo test
      run: export TMPDIR=$HOME; cargo test --verbose

  security_audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - name: Install cargo-audit
      run: cargo install cargo-audit
    - name: Run security audit
      run: cargo audit
